title: The Collective Record
author: Matt Kollada
baseurl: ""
markdown: kramdown



collections:
  newsletters:
    output: true
  reviews:
    output: true
  texts:
    output: true 


defaults:
  - scope:
      path: ""
      type: "newsletters"
    values:
      layout: "newsletter"
  - scope:
      path: ""
    values:
      layout: "default"
  